Add: Jokes Generator
nik132-eng/chrome-extensions pull request #32
Opened 2023-12-24 07:26 UTC by AaadityaG

Closing #30

2023-12-24 09:45 UTC, nik132-eng commented
please add the video link how your will work extension after adding it to the developer mode

2023-12-24 09:46 UTC, nik132-eng requested changes
add diffrent size of images

2023-12-27 10:06 UTC, AaadityaG commented
I edited the PR but, some my screen recorder is not recording so I have added SS hope you will understad!

2023-12-27 17:05 UTC, nik132-eng approved these changes

2023-12-27 17:05 UTC, merged